### ISSUE TITLE
Fields for Manage Service's quick view

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#11]
1. Remove evaluation order as a column. Now that I think about it, services are always ordered and passed that by that number.

The following fields should be displayed in the quick view:

1. Service description
2. Logo: if there is a logo path, attempt to render it and show the log instead
3. Proxy policy: if regex, show the pattern
4. Attribute policy option
5. Authorized to release to credential password
6. Authorized to release proxy granting ticket ID

The rest can be ignored.

**Comment by darkape** [comment]
Are we removing the Service Name from the display list as well?

And just a reminder, but 2 of the 12 columns are being used for buttons, so while it should still work, there may be time where the text wraps or looks a bit tight in the display.

**Comment by mmoayyed** [comment]
Service name should remain in the dashboard as a column. As such, it doesnt need to be in the quick view.

**Comment by darkape** [comment]
Ah, I misunderstood and thought you mean the listed items were to replace the table row columns since you mentioned the Service Description which is already in the table row. 

Is the description in the main table row truncated in some form, are we just displaying it twice, or should it not be in the main/quick-view row?

**Comment by mmoayyed** [comment]
I think service description better not be in the main row. A compromise would be that it gets included in both, but you have to truncate it in the main row, and show the full text in the quick view. The server does not do any sort of truncation automatically. 

The display of quick view is entirely up to you. Whatever makes the most sense, and is the easiest to understand. List item rows would probably be easiest but I dont know :)
