### ISSUE TITLE
Allow Required Handlers to be a multi-selection field

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#14]
Current functionality is, required handlers is a list out of which only one option (or none) can be selected. This isn't quite the functionality, because handlers can be stringed together and there could be more than one handler at a time required. So it would be best if the list could turn into something from which multiple items (or none) could be selected at the same time. 

Much like the "Return Allowed" list of attribute policy options.

**Comment by darkape** [comment]
Is "No Required Handler" still a possibility? If so, we'll have to do something like the "Return Allowed" where we have two options of a "No Handlers" radio and then another radio for "Required Handlers" with the multi-select list - since we don't want "None" in that list.

**Comment by mmoayyed** [comment]
Yes. The field is optional. 

- Misagh
