### ISSUE TITLE
Modify mock data for service ID to be a url

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#18]
The service ID is a string after all, it may not be a url. It's a pattern that defines a URL. The pattern could be a regex pattern such as: `https://hello.+` or it could be an ant pattern such as `http?://hello**`. 

You could update the mock data to show various options.

**Comment by mmoayyed** [comment]
I dont see this. In the dashboard, I still see numeric ids for the service id.

**Comment by darkape** [comment]
Added it to the individual mock data JSON, not the service list JSON. Will be corrected in the next PR.

**Comment by darkape** [comment]
Please verify this one as part of https://github.com/Unicon/cas/pull/21 since it was in the update as well but forgotten to be listed.
