### ISSUE TITLE
ESC key in the search field

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#24]
If possible allow the ESC key when pressed in the search field in the main dashboard, to clear the entry and focus back into the box, allowing me to type again.

**Comment by darkape** [comment]
Could do it with a key binding evnt, but it sort of goes against the standard for input fields. Also, we already have the clear (the little circle with an X inside of it) to the far right of the input field if you want to quickly clear it.

**Comment by mmoayyed** [comment]
Yes, but the problem with the X is, I have to take my hand off the keyboard. Suggestions? Could always do Ctrl+A, backspace, but it feels a bit heavy handed.

**Comment by darkape** [comment]
Problem there is it sounds like the anchor tag isn't triggering on the
tabbing order - should be able to tab to it.
