### ISSUE TITLE
Animate details dropdown on service table

### ISSUE THREAD

**Issue by doodelicious** [doodelicious/cas#3]
Using Angular animate;

**Comment by darkape** [comment]
Since we're showing and hiding it, animations don't work too well since we can't set a fixed height to easily slide the row up and down. While ng-animate may make it work, I'm personally against adding it to the app since CSS animations are cheaper to use and less libraries to add the better.

**Comment by darkape** [comment]
Haven't found a better way to do this, so going to close this issue for the 4.1 release; it can always be added to another release.
