### ISSUE TITLE
Delete services from server

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#38]
Please pull the latest from unicon/cas mgmt-webapp. 

The endpoint for deleting services is as such:

.../cas-management/deleteRegisteredService.html?id=<service numeric id>

The response back should be rendered in json with the following fields:

status: deleted/failed
serviceName: if deleted, this will be the name of the deleted service which can be used to display status updates on the page about the removal. 

Two keys are available in properties for messages:

anagement.services.status.notdeleted=The service can not be deleted.
management.services.status.deleted={0} has been successfully deleted.

**Comment by mmoayyed** [comment]
Oh, and this is a GET request.

**Comment by mmoayyed** [comment]
Note that you are most likely going to get errors because the mock data you're working on is not found and used by the server. We'll fix that eventually once the dashboard starts to render data.

**Comment by darkape** [comment]
HTTP/1.1 302 Found
Location: http://localhost:8080/cas-management/manage.html?status=failed&serviceName=

Getting a 302 response back which is being resolved as a success instead of the expected error.

**Comment by mmoayyed** [comment]
OK, I'll look into why it's not coming across as an error. The status value shows failed; so it's missing something minor to turn that into an actual error.

**Comment by mmoayyed** [comment]
This is done. Please pull

**Comment by mmoayyed** [comment]
This doesn't work. When I click the delete button, the server is never contacted to delete entries. What is the URL/parameters used and what is the format? Could you paste a sample?

**Comment by darkape** [comment]
Looks like when I made an update to it and the D&D call it stopped passing the data with it. Just leave it open until I update both to POST?

**Comment by mmoayyed** [comment]
Sure thing. I'll change the backend to use POST too. I'll make a comment here to let you know when you can pull again

**Comment by mmoayyed** [comment]
D&D and Delete is now changed to POST. Please pull.

**Comment by darkape** [comment]
Did a pull and currently getting a 403 Forbidden on both requests... Trying a delete first caused "HTTP Status 403 - Expected CSRF token not found. Has your session expired?", but after that another Delete or D&D both caused "HTTP Status 403 - Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'."

**Comment by mmoayyed** [comment]
Adam, go ahead and commit the changes as you have. This will likely require some debugging on my part. I want to see what the incoming request is, and how CAS processes it at the given endpoint.

**Comment by mmoayyed** [comment]
Adam, see this commit please:
https://github.com/Unicon/cas/commit/5bab455477904cbb54b48294cfdf0c09757170a5

In order to successfully subject AJAX request, you'll need to pass a header variable to protect against CSRF (Cross-site forgery attacks). 

See the ajax example here:
http://docs.spring.io/autorepo/docs/spring-security/3.2.0.CI-SNAPSHOT/reference/html/csrf.html

The header name and the value are part of meta tags. AJAX requests will need to set headers before submission. I realized post() cant do that, so I changed it around to a pure ajax call. Feel free to move things around. 

Also note that the header name should really be retrieved from the var. I didnt know how to do that correctly, so I hardcoded it. Please review when you get a chance:

https://github.com/Unicon/cas/commit/5bab455477904cbb54b48294cfdf0c09757170a5#diff-635c2944257f4726cf7a3fc2b82f9a71R166

With these settings, the request is properly received by the Server. You will still get errors because mock data is not found by the server, but that's OK. We'll test again once we start rendering real data. 

This should also be applicable to D&D.
