### ISSUE TITLE
Provide JSON feed to Misagh

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#39]
@darkape If you are ready, please finalize the JSON feed and pass it onto me, so I could modify the server to produce it for you. This issue only applies to the rendering of the main dashboard.

**Comment by darkape** [comment]
Below is what I'm currently using for the Manage Services dashboard mock data. I'm not sure of the db values for things like "proxyPolicy.type" (string, enum, mapped integer, etc...) but I so long as I can work with the data, and each service item is an object, I can work with it.

```
[
    {
        "assignedId": 11234,
        "serviceId": "https://hello.+",
        "name": "Apereo",
        "description": "The Apereo service for authentication.",
        "logoUrl": "http://cdn2-b.examiner.com/sites/default/files/styles/image_content_width/hash/66/4f/664f6ba9444d349a914428750cb5187e.jpg",
        "proxyPolicy": {
            "type": "refuse",
            "value": null
        },
        "attrRelease": {
            "releasePassword": true,
            "releaseTicket": true,
            "attrPolicy": {
                "type": "all"
            }
        }
    },
    {
        "assignedId": 43021,
        "serviceId": "http?://batman**",
        "name": "HTTPS and IMAPS",
        "description": "The HTTP and IMAPS service for authentication.",
        "logoUrl": null,
        "proxyPolicy": {
            "type": "regex",
            "value": "(.*)"
        },
        "attrRelease": {
            "releasePassword": true,
            "releaseTicket": false,
            "attrPolicy": {
                "type": "allowed"
            }
        }

    },
    {
        "assignedId": 90432,
        "serviceId": "http?://*.shield.net+",
        "name": "Another Service",
        "description": "Another service you can use for authentication. But if you really want, then you can pick something pre-made. Maybe?",
        "logoUrl": "http://aggressivecomix.com/wp-content/uploads/2012/08/SHIELD_Logo.png",
        "proxyPolicy": {
            "type": "regex",
            "value": "{h((.*)a)(.*)}"
        },
        "attrRelease": {
            "releasePassword": false,
            "releaseTicket": false,
            "attrPolicy": {
                "type": "mapped"
            }
        }
    }
]
```

**Comment by darkape** [comment]
Just read issue #40 and see that I'm going to need at least another field in the JSON. Please see my Q on that Issue before continuing on this one as I'll need to update this one in response to the results of it.

**Comment by mmoayyed** [comment]
Yup, I was just about to point out #40 Will review.

**Comment by darkape** [comment]
Updated the JSON.

**Comment by mmoayyed** [comment]
Is the JSON feed up to date above? What is sasCASEnabled? Should this be updated to reflect #40?

**Comment by darkape** [comment]
sasCASEnabled is the Support Access Strategy Enabled value, but to distinguish it from the SSO Enabled option I've labeled it CAS Enabled in the JSON.

**Comment by darkape** [comment]
By the way, with this provided can I expect a URL to get the services list from in the queue?

**Comment by mmoayyed** [comment]
I think we are close. I don't see options for the access strategy other than sasCASEnabled. there should be a few more. for example I dont see the one for sso enabled or one that defines access based on attributes. am I missing something?

**Comment by darkape** [comment]
A lot of the fields are missing since this is only data needed for the dashboard. Looking at #40 again, I see the request for
> Also it would be great if the main dashboard could colorize each row to determine if a service is Enabled or SSO Enabled.

but we already have 3 colored rows: 2 colors for alternating rows so they don't blend together, and a disabled color (with italicized text) for when casEnabled is false.

If we need more data (like the ssoEnabled status), then it shouldn't be color-based but additional text in the details row.

**Comment by mmoayyed** [comment]
Ah ok. The color coding is no big deal. Just cherry on top. Lets put that to the back burner for now. 

I do actually need all fields, that you could possibly pass over to the server. You can send what you need, but in order for me to account for all cases, I would need to know the name/value of every parameter that you design, so I could capture/parse them when needed.

**Comment by darkape** [comment]
Okay, I think you are asking for the Service Form JSON now, not the Service Table/Dashboard like the thread originally asked. Which one are you asking for?

**Comment by darkape** [comment]
A reminder, but any JSON I provide will be mock data I'm expecting to get, not necessarily when I will be sending - I haven't gotten to that point yet with the form data (population, validation, and submission), though it could be in same format I get it.

**Comment by mmoayyed** [comment]
Sure, understood. 

You're totally right! I mixed the two. In the end, I would need a complete reference to all fields, but what you have works for the dashboard. Lets keep this open until I develop the same model on the server side.

Thanks.

**Comment by mmoayyed** [comment]
I have made some progress on this, but do need a CAS PR to merge first before I can continue. Should happen by Monday. Stay tuned.
