### ISSUE TITLE
Tooltips are missing text

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#4]
Tooltips on the edit screen simply point to keys now. They should be replaced with their text retrieved from bundles.

**Comment by darkape** [comment]
Have updated all of the tooltips, but services.form.tooltip.publicKey.location does not have any kind of description of its purpose in the PDF. Suggestion?

**Comment by mmoayyed** [comment]
Yes. Try with: the location to the public key file used to authenticate and sign the CAS response.

**Comment by mmoayyed** [comment]
This is good. I did open up other issues. 

I will be taking a pass through tooltip descriptions to provide more info.
