### ISSUE TITLE
Add support for access strategy

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#40]
@darkape I just realized that the edit screen is missing a key piece that I never passed along. There should be another block, similar to "Username Attribute Provider Options" with the following options:

header: Service Access Strategy

Fields:

* Enabled: checkbox. Decides whether access to this service is authorized by CAS
* SSO Enabled: checkbox. Decides whether this service is allowed to participate in SSO. 
* Required Attributes: Key-Value Map. These are a set of attributes along with their values that decide whether access to this service can be granted. Design is similar to "Return Mapped" section. 
* Require All Attributes: Checkbox. Decided whether all attributes and values should be checked before access can be granted. If left unchecked, the first successful match will allow access.

You could use my descriptions here as tooltips. 

Also it would be great if the main dashboard could colorize each row to determine if a service is Enabled or SSO Enabled. For example, if Enabled=False, sort of disable the row by giving it a grey color.

If Enabled=False, all other fields should be disabled in the edit screen. 

Your JSON layout should also reflect this block.

This is a very important feature that I unfortunately missed in my original requirements. Please work on this bit first.

**Comment by darkape** [comment]
To confirm, both Enabled and SSO Enabled are available to be selected at the same time? And does not enabling the CAS one disable the other as well?

**Comment by mmoayyed** [comment]
By default, all entries are Enabled, which makes SSO Enabled and all other options available for mods. If you however uncheck Enabled, everything else should be disabled. IOW, if you disable a service, there is nothing else you can do with it. You can disable the entire form, even if Enabled is unchecked.

**Comment by mmoayyed** [comment]
Enabled=False effectively acts as if you didn't had that entry in your collection. It's useful for when you just want to disable access to that entry from CAS, because say, the application is going to a maintenance mode for 2 hours, etc.

**Comment by darkape** [comment]
Okay, so with Enabled=False they could still have SSOEnabled=true, and any existing values in the form, but it doesn't matter because it is treated as the whole service being disabled and thus ignored.

**Comment by mmoayyed** [comment]
Exactly

**Comment by mmoayyed** [comment]
So, let me clarify the case here; the server will certainly ignore the entry if it's marked as Enabled=False, but I also think on the UI, the other fields should be disabled to make clear that distinction. Enabled by default is always true, but if I happen to uncheck it, I would expect everything to become disabled.

**Comment by mmoayyed** [comment]
Also, the design of the section is a little uneasy. The attribute section is not fully expanded. I am thinking it might be better to encapsulate both "Require All Attributes" checkbox and the entire attributes section below it into a separate inner section with a title "Role-based Access Control". Similar to how "Principle Attribute Repository Options" is placed on the page.

**Comment by darkape** [comment]
I am against disabling all of the fields when set casEnabled=false; that is a lot of data fields that have to be keyed off of a single value and I would personally expect to be able to continue editing the data even if I were to un-check the Enabled box.

If you want to make it stand out, we change the headline from "Support Access Strategy" to "Support Access Strategy - [bold]DISABLED[/bold]" or something, but disabling the whole form would be a bad UX. It _might_ work if we had Enable as the very first form field, but that panel didn't look right being up there, which is why I moved it down.

----
As for the design, I tried to make it so it would not cause the page to expand much further down since I already have to scroll the page to see the SAS panel's content, and then it goes back up for the Username Attribute Provider Options panel (and back down). What you suggest can be done, and though I'm only using dummy data since I lack any real data, I believe it currently works... Quick example, currently "attribute_hander_names_are_long" fits both in the Source and CAS Attribute columns without an issue.

**Comment by mmoayyed** [comment]
>I am against disabling all of the fields when set casEnabled=false; that is a lot of data fields that have to be keyed off of a single value and I would personally expect to be able to continue editing the data even if I were to un-check the Enabled box.

But there is no reason to actually allow you to keep editing data, if you have the service disabled. That's a clear distinction. In fact, you could, by accident, disable a service and continue editing data and none of it will actually matter because the whole thing is written off by the server. So we need to make that explicitly clear that when you disable a service, you can do *absolutely nothing* to that entry, because the server will do absolutely nothing for that entry. There is no point in editing data for an entry that has no use from the server perspective. 

I am not sure what it's considered bad UX; if the argument is based on the number of fields that need to be disabled, then so be it. JQuery does that sort of thing really well.

**Comment by mmoayyed** [comment]
Changing the title is also not an appropriate strategy, because that implies that you have disabled that section, which is untrue. Enabled=false basically acts as if you never had that entry in the first place and so we need make sure the app is following what the server actually does in real time.

**Comment by mmoayyed** [comment]
No you make a very good argument about the placement of the panel. Excellent point. We could maybe move the checkout box out of that panel and make it visible at the very top? maybe? Things are logically grouped together that way, but they dont have to be displayed that way. You could move them around if that makes it easier to explain.

**Comment by darkape** [comment]
Talked with Jodie and we both agree that the disabling of the form is a bad user experience, but we talked about how to better warn the user that even though they can edit the data, it won't matter until they enable the service again. I'm going to update the form layout so you can see the results of what we discussed and we can work from there.

----
I'd like to request more information about Require All Attributes, Required Attributes, and how the value of Require All Attributes affects/matters-to the key-mapped Required Attributes rows. Neither Jodie nor I really understand the fields or their relationship, so can't properly consider what the best layout would be for it. It may change again once we get live data, but that will considered when it happens.

**Comment by mmoayyed** [comment]
Let me see if I can help with a bit more description:

The access strategy section basically tries to decide if the requesting application is authorized to use CAS server for authentication. There are generally 3 cases:

1. The application is not authorized, where enabled=false
2. The application is authorized, but CAS will not initiate an SSO session and will challenge the user for credentials every time, where SSOEnabled=false

Then there is the 3rd option, where access to the application is only authorized if the authenticated user has the configured attribute names with their attribute values. For example, in the required attributes, you'd configure the entry to say "CN=Misagh" and "GivenName=Jedi". 

Then upon access time, CAS will examine the authenticated user and goes through the required attributes list. If it finds an attribute CN with a value Misagh, OR, if it finds an attribute GivenName with a value Jedi, it will allow access. Otherwise, it will reject it. 

The Require All attributes turns that OR, into an AND. In other words, while by default only a single match is required for access, that option makes sure every attribute configured is examined and matched before access is granted. 

Does that help?

**Comment by mmoayyed** [comment]
Looks good. I like the checkbox at the time. Certain fields however are captioned as red. Is that intentional? Fine either way.
