### ISSUE TITLE
Tweak the dashboard service obj

### ISSUE THREAD

**Issue by darkape** [doodelicious/cas#46]
OLD/CURRENT:

```json
        "attrRelease": {
            "releasePassword": true,
            "releaseTicket": true,
            "attrPolicy": {
                "type": "all"
            }
        }
 ```
 
NEW:
```json
        "attrRelease": {
            "releasePassword": true,
            "releaseTicket": true,
            "attrPolicy": "all"
        }
```
Basically, just removing the nested 'type' since we don't care about the 'value' that typically would be associated with it.

**Comment by mmoayyed** [comment]
This should be fixed. Pushed to remote. Leaving the issue open until app is able to parse.

**Comment by darkape** [comment]
heh, already added, but forgot to add it to the list for the next PR, so please be aware.
