### ISSUE TITLE
JSON feed for Form Submission 

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#48]
Please attach a JSON feed for all candidate fields that could be submitted via the form.

**Comment by darkape** [comment]
PURELY for the retrieval, here is the format:
[
    {
        "assignedId": 11234,
        "supportAccess": {
            "casEnabled": true,
            "ssoEnabled": true,
            "requireAll": false,
            "requiredAttr": {
                "uid": "Apereo"
            }
        },
        "serviceId": "https://hello.+",
        "name": "Apereo",
        "description": "The Aperep service for authentication.",
        "type": 0,
        "oauth": {
            "clientSecret": "",
            "clientId": "",
            "bypass": 0
        },
        "theme": "theme01",
        "evalOrder": 1,
        "requiredHandlers": [
            "reqHandler02"
        ],
        "logoUrl": "http://www.everythingisawesome.com/images/captain-awesome.jpg",
        "logoutUrl": null,
        "logoutType": "none",
        "userAttrProvider": {
            "type": "default",
            "value": null
        },
        "publicKey": {
            "location": "myLocation",
            "algorithm": "RSA"
        },
        "proxyPolicy": {
            "type": "refuse",
            "value": null
        },
        "attrRelease": {
            "releasePassword": true,
            "releaseTicket": true,
            "attrFilter": "*",
            "attrOption": "default",
            "cachedTimeUnit": null,
            "cachedExpiration": null,
            "attrPolicy": {
                "type": "all",
                "attributes": {}
            }

        }
    }
]

As for the submission, I should be able to send it back in the same format. That said, Still not sure how well those attribute list fields will work, but this is the best guess at this time.

**Comment by mmoayyed** [comment]
what are the possible values for type? Can you elaborate? 
Shouldn't "bypass"  be true/false?
If a field value is null/blank, could work with it missing from the JSON response? If it isn't there, assume it's null/blank?

**Comment by darkape** [comment]
Honestly, was expecting you to update me with the possible values of the various types, but I can explain as how I currently have them if it helps:
type: 'cas'/'oauth'
userAttrProvider.type: 'default'/'anon'/'attr'
proxyPolicy.type: 'refuse'/'regex'
attrRelease.attrOption: 'default'/'cached'
attrRelease.attrPolicy.type: 'all'/'allowed'/'mapped'
(These can be String, Enumerations, or specifically mapped Integers, whatever is easier to store/pass, I just need to know the assigned values if mapped.)

Yeah, oauth can be true/false, I think I just missed it when I updated the rest since I originally had all false values as 0 and true values as 1 originally.

If a field value is null or "", it can have a value, but SHOULD still be part of the JSON I get since it is likely that those fields just weren't required and left blank the first time it was saved or such. As for data sent to the server, I believe I should always be sending the fields even if their contents are empty.

**Comment by darkape** [comment]
Going to need a list of the different Theme, Required Handlers, SAS Required Attributes, and Attr Policy Options for both Return Allowed & Return Mapped. If any of these are based off of db data, then I'll need at least one call to retrieve that information. If these are ones that the user themselves adds, which I doubt but I'll mention anyways, then the form will need to change a bit, but the data should still be in the same structure.

**Comment by mmoayyed** [comment]
These values are retrieved off of db and other config files. They are not fixed. Could you get them all in the same call that gets the entire JSON response?

**Comment by darkape** [comment]
No, there should be 1 call for the service information by itself and another separate call for when we want the database variables; the db vars can be called a single time when they log in, but the service details call will be made every time they click an EDIT button of a service from the dashboard.

**Comment by mmoayyed** [comment]
>No, there should be 1 call for the service information by itself and another separate call for when we want the database variables; 

Why? Why cant you just parse on JSON blob?

**Comment by mmoayyed** [comment]
The db vars cannot be called once; they are variable. They may change on every call.

**Comment by mmoayyed** [comment]
Submit a request getService.html as GET with id=<assignedId>. Result would be:

```json
{
  "availableAttributes": [
    "eduPersonAffiliation",
    "groupMembership",
    "uid"
  ],
  "availableUsernameAttributes": [
    "eduPersonAffiliation",
    "groupMembership",
    "uid"
  ],
  "assignedId": 10000001,
  "serviceId": "^(https|imaps):\/\/.*",
  "name": "HTTPS and IMAPS",
  "description": "This service definition authorized all application urls that support HTTPS and IMAPS protocols.",
  "logoUrl": null,
  "theme": null,
  "evalOrder": 0,
  "requiredHandlers": [
    
  ],
  "logoutUrl": null,
  "supportAccess": {
    "casEnabled": true,
    "ssoEnabled": true,
    "requireAll": true,
    "requiredAttr": {
      
    }
  },
  "type": "CAS",
  "oauth": {
    "clientSecret": null,
    "clientId": null,
    "bypass": false
  },
  "logoutType": "BACK",
  "userAttrProvider": {
    "value": null,
    "type": "DEFAULT"
  },
  "publicKey": {
    "location": null,
    "algorithm": null
  },
  "proxyPolicy": {
    "type": "REFUSE",
    "value": null
  },
  "attrRelease": {
    "releasePassword": false,
    "releaseTicket": false,
    "attrFilter": null,
    "cachedTimeUnit": null,
    "cachedExpiration": 0,
    "attrPolicy": {
      "type": "ALLOWED",
      "attributes": [
        [
          
        ]
      ]
    },
    "attrOption": "DEFAULT",
    "mergingStrategy": "DEFAULT"
  }
}
```

Note the addition of two blocks that give you a list of available attributes for usernames, etc. These can be made into a separate calls. There is also a merging Strategy now.

**Comment by mmoayyed** [comment]
Fixed a few issues. Final result:

```json
{
  "availableAttributes" : [ "eduPersonAffiliation", "groupMembership", "uid" ],
  "availableUsernameAttributes" : [ "eduPersonAffiliation", "groupMembership", "uid" ],
  "assignedId" : 52497044623301,
  "serviceId" : "http://localhost:8080/cas-management/login/cas",
  "name" : "Services Management Web Application",
  "description" : "Services Management Web Application",
  "logoUrl" : null,
  "theme" : null,
  "evalOrder" : 2,
  "requiredHandlers" : [ ],
  "logoutUrl" : null,
  "supportAccess" : {
    "casEnabled" : true,
    "ssoEnabled" : true,
    "requireAll" : true,
    "requiredAttr" : { }
  },
  "type" : "cas",
  "oauth" : {
    "clientSecret" : null,
    "clientId" : null,
    "bypass" : false
  },
  "logoutType" : "back",
  "userAttrProvider" : {
    "value" : null,
    "type" : "default"
  },
  "publicKey" : {
    "location" : null,
    "algorithm" : "RSA"
  },
  "proxyPolicy" : {
    "type" : "refuse",
    "value" : null
  },
  "attrRelease" : {
    "releasePassword" : false,
    "releaseTicket" : false,
    "attrFilter" : null,
    "cachedTimeUnit" : null,
    "cachedExpiration" : 0,
    "attrPolicy" : {
      "type" : "allowed",
      "attributes" : [ [ ] ]
    },
    "attrOption" : "default",
    "mergingStrategy" : "default"
  }
}
```

Changes are pushed to Unicon's remote

**Comment by darkape** [comment]
It would probably be better if you put all of the service data actually in a service object and form options in another object like { formOptions: {}, service: {} }, but I can work with it as is, though the data I send back to you on save may also contain some extra stuff like the like the availableAttributes and availableUsernameAttributes.

Q: Why is attrPolicy.attributes a double-array and supportAccess.requiredAttr an object? I notice attrPolicy.attributes change from being attrPolicy.value as well, but was there a reason other than naming convention?

**Comment by mmoayyed** [comment]
> I can work with it as is, though the data I send back to you on save may also contain some extra stuff like the like the availableAttributes and availableUsernameAttributes.

That's fine. When I render the data back into Java objects, those fields will just be ignored, regardless of whether there is data there or not. 

I'll look into a double-array issue. I think the code is wrapping the attribute list/array into another array. Probably just need to remove the outer wrap.

**Comment by darkape** [comment]
Shouldn't supportAccess.requiredAttr also be an array since the other is then?

**Comment by darkape** [comment]
Also, please provide an example of what a value inside of the array should look like.

**Comment by mmoayyed** [comment]
supportAccess.requiredAttr is a map, which is why I think you get it as an object. You need both names mapped to many values.

The other is sort of variable, depending on type. If it's ALL, you don't get anything in the JSON response. everything is allowed. If it's allowed, you get a list which turns into an array in JSON. If it's mapped, you get an object. 

examples coming up.

**Comment by darkape** [comment]
For attrPolicy.attributes the data type should be consistent, but I think I can make it work, though I'll have to add in even more extra processing after the get and before the save.

**Comment by mmoayyed** [comment]
Example 1:

```json
  "supportAccess" : {
    "casEnabled" : false,
    "ssoEnabled" : false,
    "requireAll" : true,
    "requiredAttr" : {
      "cn" : [ "v1" ],
      "memberOf" : [ "v4, v5, v6" ]
    }
  },
```

**Comment by mmoayyed** [comment]
Example 2:

```json
  "attrRelease" : {
    "releasePassword" : false,
    "releaseTicket" : false,
    "attrFilter" : "\\w+",
    "cachedTimeUnit" : null,
    "cachedExpiration" : 0,
    "attrPolicy" : {
      "type" : "allowed",
      "attributes" : [ "1", "2", "3" ]
    },
    "attrOption" : "default",
    "mergingStrategy" : "default"
  }
```

**Comment by mmoayyed** [comment]
Example 3:

```json
  "attrRelease" : {
    "releasePassword" : false,
    "releaseTicket" : false,
    "attrFilter" : null,
    "cachedTimeUnit" : null,
    "cachedExpiration" : 0,
    "attrPolicy" : {
      "type" : "mapped",
      "attributes" : {
        "attr1" : "newattr1",
        "attr2" : "newattr3"
      }
    },
    "attrOption" : "default",
    "mergingStrategy" : "default"
  }
```

**Comment by darkape** [comment]
We have 
```
"availableAttributes" : [ "eduPersonAffiliation", "groupMembership", "uid" ],
"availableUsernameAttributes" : [ "eduPersonAffiliation", "groupMembership", "uid" ],
```
but is this for both Attribute Policy Options -AND- Support Access Strategy? Ended up mapping it that way only to realize afterwards it was odd. If they are different, it would be better to group them under the appropriate sub-object. 

Also, shorter names are justice! I'd change something like "availableAttributes" to "availAttr" b/c makes the code a bit easier to follow, though honestly not sure where either of those belong since their just in the base object with generic names. ^^, The things we see so much easier once we've put them in place~

**Comment by mmoayyed** [comment]
These are used for you to populate the dropdown fields for username attributes (when it's principal based) and attributes that may be configured for policy from which the user can select which is allowed and/or mapped. 

what works for you in terms of naming and structure? I am in a giving mood :)

**Comment by darkape** [comment]
That is fine for Attribute Policy Options - Return Allowed, but not for Mapped as we're currently basing it on attrRelease.attrPolicy.attributes, so it shouldn't be based on both; ideally it would be populated with each option pair and the value of the param would just be null (or empty string) if they didn't provide a value. The data I send back would be mapped accordingly.

I'll also need the options for the Service Access Strategy Attributes, which will be handled the same way as the Mapped.

As for the names, lets deal with that once we get the structure resolved.

**Comment by mmoayyed** [comment]
OK, sure. I can make that happen.

**Comment by mmoayyed** [comment]
So let me explain; the data is not "based" on anything. There is purely used for you to render what the available values are. These are the attributes the user is allowed to "work with", via whatever option. That's a list that you can use to populate the screen, and then allow the user to provide values, add/remove attributes, etc. 

Note that you also need to find a way to add/remove attributes back and forth. For example:

- User allows 3 out of 5
- Or user maps 3 out of 5
- Or user says I require 2 attribute names with the following values for service access

The data that you send, does not have to map to what you see here. This is purely for rendering. The server will ignore both those fields, as it already knows what the available attributes are. Even if you send them back, it will forget about them. So there is no need for me to pass empty/null values for you.
