### ISSUE TITLE
Form endpoint for service submissions

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#50]
There will be a "xyz.html" as a POST to accept JSON data and update the entry.

I can work on adding the entry, but do need #48 before I can proceed. Will provide the endpoint later on once the format is mapped out.

**Comment by mmoayyed** [comment]
Submit a POST with JSON in the body to saveService.html.

**Comment by darkape** [comment]
So set it up but I get a response of "HTTP Status 405 - Request method 'POST' not supported"

My $.ajax call looks like this:
                    type: 'post',
                    url: '/cas-management/saveService.html',
                    data: serviceForm.serviceData, // same serviceData obj we're getting from the server
                    headers: httpHeaders, // { csrfHeader: csrfToken }

**Comment by mmoayyed** [comment]
Because I am an idiot :) I had set the endpoint to be on GET. Fixed and pushed. 

Note that the save method is still being worked out. Likely needs troubleshooting from me a bit more, but go ahead and set it up, pass data and I'll do the rest.
