### ISSUE TITLE
New service type for oauth_callback_authz

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#52]
Our services types are CAS and OAuth. Please add one more for "OAuth Callback Authorize". The type description in the JSON would be "oauth_callback_authz". 

No changes to the form needed. Just a new type. OAuth Callback Authorize = CAS as far as changes go. Other Oauth fields should hide.

**Comment by darkape** [comment]
Easily done.

**Comment by darkape** [comment]
Is the service type fixed values or generated from the db? If fixed, I need to make fields for them in the messages table.

**Comment by mmoayyed** [comment]
Fixed
