### ISSUE TITLE
More options for Cached attributes

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#55]
When I select cached for the attributes option, I get a time unit and a duration. Sweet bananas. 

Please allow for a dropdown with the label "Merging Strategy" and the following options:

1. DEFAULT
2. ADD
3. MULTIVALUED
4. REPLACE

**Comment by darkape** [comment]
Are these fixed values or from the database? Asking because need to know if they need entries in the messages file.

**Comment by mmoayyed** [comment]
They are fixed

**Comment by mmoayyed** [comment]
I see a NONE in the dropdown. Is that the same as DEFAULT? I think the JSON data you consume has "default" should that be changed?

**Comment by darkape** [comment]
Huh, not sure how that one got mixed in. Will fix.
