### ISSUE TITLE
Theme/Required Handler form changes

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#56]
Please change the following fields to be:

1. Theme - single input field
2. Required Handlers - comma separated values

**Comment by darkape** [comment]
Thought we were going to have Handlers be a textarea with each new line a new value?

**Comment by mmoayyed** [comment]
Sure. That will work too.

**Comment by mmoayyed** [comment]
Think I created the issue before we discussed this. Proceed with text areas plz.
