### ISSUE TITLE
Fix test cases

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#57]

**Comment by darkape** [comment]
Is there a reason to fix the dummy data since we're close to having live data calls and #51 is to Remove the Dummy Data?

**Comment by mmoayyed** [comment]
Ultimately, I think we should remove it to keep the codebase clean. Dummy data would be relevant if we had test cases. When I get to submitting the final PR to CAS, I am sure I'll be asked to remove dummy data.

**Comment by darkape** [comment]
Since we're going to remove the dummy data, I don't see much reason to update it all, especially since should be using live data soon. I'll of course update at least one so we can still update the form until I do get live data results, but not the others.
