### ISSUE TITLE
The edit/add screen should update its title

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#6]
The title/header on the page right now is always "addServiceView".

**Comment by darkape** [comment]
What should this be saying, something like "Add Service" or "Edit Service" based on if we're adding a new or editing an existing one?

**Comment by mmoayyed** [comment]
Exactly

**Comment by mmoayyed** [comment]
This doesn't work. If I click Edit in the dashboard, the page still shows me " Add Service".

**Comment by darkape** [comment]
The edit state is not currently enabled - have to get routes setup for that. What was primarily fixed for this was the states were setup with conditional tags so it either shows a now working message of 'Add Service' when assignedID is null and will later show 'Edit Service' once we have routes working so we can tell an assignedID has been passed.

**Comment by mmoayyed** [comment]
OK cool. I'll wait until you have routes so I can verify this then.

**Comment by darkape** [comment]
Requires #25 be complete. (Adding this in so we have a list on the other issue to know which ones can then be closed once it is complete.)

**Comment by darkape** [comment]
Forgot, but I did make edits so you can see when a form is being edited now, though it isn't pulling in the mock data yet. If you click the Edit Buttons the actionPanel is now 'edit', and thus you see 'Edit Service' in the headline. If you use either of the Add New Service links it shows the 'Add Service' headline.
