### ISSUE TITLE
Submit evaluation order a random int value when saving new service.

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#60]

**Comment by darkape** [comment]
Rather than random, making it the max evalOrder we've already received (from the getServices call) + 1.

**Comment by mmoayyed** [comment]
Sounds good. I want to make sure we avoid collisions where we can. Your solution is far simpler.

**Comment by darkape** [comment]
need evalOrder to be in the data for the getServices.html call to get this working; forgot we pulled it out once we removed the field from the row

**Comment by mmoayyed** [comment]
Pushed
