### ISSUE TITLE
Service access strategy settings are not set

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#63]

**Comment by darkape** [comment]
All of the checkboxes are updating fine, but getting an error when trying to save it with a value in the first attribute field; it looks like mapping for the the value in the field is breaking it: http://pastebin.com/FGmG5LAi

**Comment by darkape** [comment]
Forgot about it, but currently populating the table with the data from formData.availableAttributes since there is not list for Support Access, so might be because of that. Can fix once I get a proper listing.

**Comment by mmoayyed** [comment]
For this to work, I think you need to send data as

```
"supportAccess" : {
      "casEnabled" : true,
      "ssoEnabled" : true,
      "requireAll" : true,
      "requiredAttr" : {
        "cn" : [ "v1, v2, v3" ],
        "memberOf" : [ "v4, v5, v6" ]
      }
    },
```

Note the brackets.

**Comment by darkape** [comment]
Will convert those to textareas to allow the multiple lines usage - each line is a new value similar to the Required Handlers.

**Comment by darkape** [comment]
Heh, still had Issue #54 open, so no wonder it wasn't working. ^_^,

**Comment by mmoayyed** [comment]
requireAll and enableSSO checkboxes dont seem to pass data back to the server correctly. If I uncheck them, and press save I see true is passed for both of them. I can never uncheck them it seems. 

JSON that is passed when they are both unchecked is:

```json
{"assignedId":10000001,"serviceId":"^(https|imaps)://.*","name":"HTTPS and IMAPS","description":"This service definition authorized all application urls that support HTTPS and IMAPS protocols.","logoUrl":null,"theme":null,"evalOrder":0,"requiredHandlers":[],"logoutUrl":null,"supportAccess":{"casEnabled":true,"ssoEnabled":true,"requireAll":true,"requiredAttr":{"uid":[],"groupMembership":["hello, world"],"eduPersonAffiliation":["misagh, test"]},"requiredAttrStr":{"eduPersonAffiliation":"misagh, test","groupMembership":"hello, world","uid":""}},"type":"cas","oauth":{"clientSecret":null,"clientId":null,"bypass":false},"logoutType":"back","userAttrProvider":{"value":null,"type":"default","valueAnon":"","valueAttr":""},"publicKey":{"location":null,"algorithm":"RSA","valid":false},"proxyPolicy":{"type":"refuse","value":null},"attrRelease":{"releasePassword":false,"releaseTicket":false,"attrFilter":null,"cachedTimeUnit":null,"cachedExpiration":0,"attrPolicy":{"type":"allowed","attributes":[],"allowed":[]},"attrOption":"default","mergingStrategy":"default"},"reqHandlersStr":""}: 
```

**Comment by mmoayyed** [comment]
Also, when the server passes true for both, they are not set either.
