### ISSUE TITLE
Proxy policy option is not set when sent from server

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#64]

**Comment by darkape** [comment]
Did send ```proxyPolicy: {type: "regex", value: "ggfgf"}``` on saveService.html, but when doing another getService call it was ```"proxyPolicy" : {"type" : "refuse", "value" : null}``` again. Please check to see why it didn't save on your side.

**Comment by mmoayyed** [comment]
Pushed fix. Mapping was weird on server.

**Comment by darkape** [comment]
Confirmed fixed.
