### ISSUE TITLE
Principal attribute option is not set on form

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#65]

**Comment by darkape** [comment]
I am sending the data for this field (if I'm looking at the right one) as
```
userAttrProvider: {
    type: "attr"
    value: "groupMembership"
    valueAnon: ""
    valueAttr: "groupMembership"
}
```
When I to a get back though I get the type as "default" again even though the value has properly been sent. Please check this on your end.

**Comment by mmoayyed** [comment]
The block would need to be either:

```json
"userAttrProvider" : {
      "value" : "aGVsbG93b3JsZA==",
      "type" : "anon"
    },
```

OR

```json
    "userAttrProvider" : {
      "value" : "cn",
      "type" : "attr"
    },
```

OR

```json
    "userAttrProvider" : {
      "value" : null,
      "type" : "default"
    },
```

Pushed a fix to account for the attr option.

**Comment by darkape** [comment]
Yeah, I understand that valueAnon and valueAttr are just extras I created. Appears to be working now except that under Username Attribute Provider Options the Salt Setting string is being converted from what I saved to something else when I re-load the same Edit Service.

**Comment by mmoayyed** [comment]
Pushed fix.
