### ISSUE TITLE
Logout type values

### ISSUE THREAD

**Issue by mmoayyed** [doodelicious/cas#73]
Logout type values are a bit strange. Either they all should be prefixed with an index, (None isn't), or better yet, remove indexes and just have their text show.

**Comment by darkape** [comment]
I currently have these values set like this:
```
                    {name: 'None',              value: ''},
                    {name: '1 - BACK_CHANNEL',  value: 'back'},
                    {name: '2 - FRONT_CHANNEL', value: 'front'}
```
Should the value actually be the prefixed number instead of strings?

**Comment by mmoayyed** [comment]
Think it might be better if you had:

```
{name: 'None', value: ''},
{name: 'Back Channel',  value: 'back'},
{name: 'Front Channel', value: 'front'}
```

**Comment by darkape** [comment]
Can do that, I just left them how they were when I inherited the code, so figured that was how the text was suppose to be. :)
